AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 160
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: 'no_space'
Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'spec/factories/workflows.rb'
Layout/ArrayAlignment:
  Exclude:
    - 'spec/factories/workflows.rb'
Layout/HashAlignment:
  Exclude:
    - 'spec/factories/workflows.rb'
Layout/SpaceAroundOperators:
  Exclude:
    - 'spec/factories/workflows.rb'
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'spec/support/*.rb'
    - 'spec/factories/*.rb'
Metrics/MethodLength:
  Description: 'Avoid methods longer than 12 lines of code.'
  Max: 12

Style/NumericLiterals:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: slashes
# disable 'Missing top-level class documentation' warning
Style/Documentation:
  Enabled: false
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

# new linters - opt in
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true