apiVersion: batch/v1
kind: Job
metadata:
  generateName: eras-corp-partners-sync-
spec:
  template:
    metadata:
      name: eras-corp-partners-sync
    spec:
      containers:
      - name: eras-corp-partners-sync
        image: ghcr.io/zooniverse/eras
        env:
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: RAILS_ENV
              value: production
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: eras-production
                  key: rails-master-key
        command: ['ruby', './scripts/user_group_membership_classification_backfill.rb']
      restartPolicy: Never
    backoffLimit: 2
