name: Manually Sync Eras Corporate User Group Sync

on:
  workflow_dispatch:

jobs:
  manual_sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_AKS }}

    - name: Set the target AKS cluster
      uses: Azure/aks-set-context@v3
      with:
        cluster-name: microservices
        resource-group: kubernetes

    - name: Modify & apply template
      run: kubectl create -f kubernetes/manual_corp_user_group_sync.yml
      